[versions]
agp     = "8.8.0"
kotlin  = "1.9.24"
coreKtx = "1.15.0"
okhttp  = "5.0.0-alpha.14"

[libraries]
androidx-core-ktx  = { group = "androidx.core", name = "core-ktx",  version.ref = "coreKtx" }
okhttp             = { module = "com.squareup.okhttp3:okhttp",      version.ref = "okhttp" }

[plugins]
android-library = { id = "com.android.library",          version.ref = "agp" }
kotlin-android  = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
